sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: xct001112
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: LTAI5tNsH3gtBmEgc7xEpWrS
    accessKeySecret: SZzbCC49fZMjStOHkM3i4BzkkTWf8m
    bucketName: web-tils-123
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  wechat:
    appid: wx466b1bf9e199bf8b
    secret: 882b8cf9aa94e52b5350ae53b6967ac4